export const GET_DATA = 'GET_DATA';
export const RESET = 'RESET';
export const INCREMENT_METRIC_SCORE = 'INCREMENT_METRIC_SCORE';
export const DECREMENT_METRIC_SCORE = 'DECREMENT_METRIC_SCORE';
export const FETCH_CURRENT_USER = 'FETCH_USER';
